name: Delete Package Version

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to be deleted package@version'
        required: true

jobs:
  delete-package-version:
    runs-on: ubuntu-latest
    if: >-
      github.ref == 'refs/heads/main' &&
      (github.actor == 'JackLian' || github.actor == 'liujuping')

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Delete Package Version
      run: |
        npm unpublish ${{ github.event.inputs.version }}
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
